INSERT INTO "module_auto_action" VALUES(4,76);
INSERT INTO "module_auto_action" VALUES(6,23);
INSERT INTO "module_auto_action" VALUES(6,25);
INSERT INTO "module_auto_action" VALUES(9,20);
INSERT INTO "module_auto_action" VALUES(13,21);
INSERT INTO "module_auto_action" VALUES(14,22);
INSERT INTO "module_auto_action" VALUES(16,25);
INSERT INTO "module_auto_action" VALUES(17,24);
INSERT INTO "module_auto_action" VALUES(26,33);
INSERT INTO "module_auto_action" VALUES(26,34);
INSERT INTO "module_auto_action" VALUES(28,21);
INSERT INTO "module_auto_action" VALUES(28,25);
INSERT INTO "module_auto_action" VALUES(28,32);
INSERT INTO "module_auto_action" VALUES(28,40);
INSERT INTO "module_auto_action" VALUES(29,43);
INSERT INTO "module_auto_action" VALUES(31,38);
INSERT INTO "module_auto_action" VALUES(31,41);
INSERT INTO "module_auto_action" VALUES(35,42);
INSERT INTO "module_auto_action" VALUES(35,62);
INSERT INTO "module_auto_action" VALUES(35,63);
INSERT INTO "module_auto_action" VALUES(35,64);
INSERT INTO "module_auto_action" VALUES(35,65);
INSERT INTO "module_auto_action" VALUES(35,66);
INSERT INTO "module_auto_action" VALUES(35,67);
INSERT INTO "module_auto_action" VALUES(35,68);
INSERT INTO "module_auto_action" VALUES(35,69);
INSERT INTO "module_auto_action" VALUES(35,70);
INSERT INTO "module_auto_action" VALUES(35,71);
INSERT INTO "module_auto_action" VALUES(35,73);
INSERT INTO "module_auto_action" VALUES(35,83);
INSERT INTO "module_auto_action" VALUES(35,91);
INSERT INTO "module_auto_action" VALUES(37,39);
INSERT INTO "module_auto_action" VALUES(37,61);
INSERT INTO "module_auto_action" VALUES(79,81);
INSERT INTO "module_auto_action" VALUES(80,82);


INSERT INTO "role" VALUES (1,'Администратор','yes');
INSERT INTO "role" VALUES (2,'Работник','no');
INSERT INTO "role" VALUES (3,'Начальник отдела','no');


INSERT INTO "module" VALUES (1,'role','Роли');
INSERT INTO "module" VALUES (2,'employee','Сотрудники');
INSERT INTO "module" VALUES (3,'department','Подразделения');
INSERT INTO "module" VALUES (4,'company','Контрагенты');
INSERT INTO "module" VALUES (6,'variable','Дополнительные поля');
INSERT INTO "module" VALUES (11,'message','Сообщения');
INSERT INTO "module" VALUES (12,'file','Файловый менеджер');
INSERT INTO "module" VALUES (13,'calendar','Календарь');
INSERT INTO "module" VALUES (14,'report','Отчеты');
INSERT INTO "module" VALUES (26,'office','Должности сотрудников');
INSERT INTO "module" VALUES (34,'news','доска обьявлений компании');
INSERT INTO "module" VALUES (40,'schedule','планировщик мероприятий');
INSERT INTO "module" VALUES (41,'schedule-period','периоды мероприятий');
INSERT INTO "module" VALUES (42,'schedule-type','типы мероприятий');
INSERT INTO "module" VALUES (45,'organizer','ежедневник');
INSERT INTO "module" VALUES (46,'uvedoml','Модуль общесистемных уведомлений');
INSERT INTO "module" VALUES (47,'journal','Журнал ККС СИТО');
INSERT INTO "module" VALUES (48,'slovar','Словарь ККС СИТО');
INSERT INTO "module" VALUES (49, 'category', 'Категории и шаблоны ККС СИТО');
INSERT INTO "module" VALUES (50, 'rubrics', 'Рубрикаторы ККС СИТО');



INSERT INTO "module_action" VALUES (1,6,'view','Просмотр','yes');
INSERT INTO "module_action" VALUES (2,6,'delete','Удаление','yes');
INSERT INTO "module_action" VALUES (3,6,'edit','Редактировать','yes');
INSERT INTO "module_action" VALUES (4,2,'view','Просмотр','yes');
INSERT INTO "module_action" VALUES (5,2,'delete','Удаление','yes');
INSERT INTO "module_action" VALUES (6,2,'edit','Редактировать','yes');
INSERT INTO "module_action" VALUES (7,4,'view','Просмотр','yes');
INSERT INTO "module_action" VALUES (8,4,'delete','Удаление','yes');
INSERT INTO "module_action" VALUES (9,4,'edit','Редактировать','yes');
INSERT INTO "module_action" VALUES (11,5,'view','Просмотр','yes');
INSERT INTO "module_action" VALUES (12,5,'delete','Удаление','yes');
INSERT INTO "module_action" VALUES (13,5,'edit','Редактировать','yes');
INSERT INTO "module_action" VALUES (14,3,'view','Просмотр','yes');
INSERT INTO "module_action" VALUES (26,8,'view','Просмотр','yes');
INSERT INTO "module_action" VALUES (45,11,'delete','Удаление','yes');
INSERT INTO "module_action" VALUES (46,11,'edit','Редактировать','yes');
INSERT INTO "module_action" VALUES (47,12,'view','Просмотр каталогов','yes');
INSERT INTO "module_action" VALUES (48,12,'delete','Удаление','yes');
INSERT INTO "module_action" VALUES (49,12,'edit','Загрузка','yes');
INSERT INTO "module_action" VALUES (50,12,'add-directory','Добавление директорий','no');
INSERT INTO "module_action" VALUES (51,12,'move','Перенос файлов и каталогов','no');
INSERT INTO "module_action" VALUES (52,12,'rename','Переименовывание каталогов и файлов','no');
INSERT INTO "module_action" VALUES (60,12,'change-role','Изменение доступа','no');
INSERT INTO "module_action" VALUES (99,17,'rows_conf','настройка отображаемых столбцов','yes');
INSERT INTO "module_action" VALUES (171,34,'view','Просмотр доски обьявлений','yes');
INSERT INTO "module_action" VALUES (172,34,'edit','Настройка доски объявлений','yes');
INSERT INTO "module_action" VALUES (173,34,'preview','Предпросмотр объявления','yes');
INSERT INTO "module_action" VALUES (174,39,'planned-payment','','yes');
INSERT INTO "module_action" VALUES (175,40,'view','','yes');
INSERT INTO "module_action" VALUES (176,40,'edit','','yes');
INSERT INTO "module_action" VALUES (177,40,'delete','','yes');
INSERT INTO "module_action" VALUES (178,41,'delete','','yes');
INSERT INTO "module_action" VALUES (179,41,'edit','','yes');
INSERT INTO "module_action" VALUES (180,41,'view','','yes');
INSERT INTO "module_action" VALUES (181,42,'delete','','yes');
INSERT INTO "module_action" VALUES (182,42,'view','','yes');
INSERT INTO "module_action" VALUES (183,42,'edit','','yes');
INSERT INTO "module_action" VALUES (184,43,'delete','','yes');
INSERT INTO "module_action" VALUES (185,43,'edit','','yes');
INSERT INTO "module_action" VALUES (186,43,'move','','yes');
INSERT INTO "module_action" VALUES (187,43,'view','','yes');
INSERT INTO "module_action" VALUES (188,43,'select-org-soglas','','yes');
INSERT INTO "module_action" VALUES (189,44,'view','','yes');
INSERT INTO "module_action" VALUES (190,44,'delete','','yes');
INSERT INTO "module_action" VALUES (191,44,'edit','','yes');
INSERT INTO "module_action" VALUES (192,44,'select-org','','yes');
INSERT INTO "module_action" VALUES (193,44,'table','','yes');
INSERT INTO "module_action" VALUES (194,46,'notice-view','Просмотр общесистемных уведомлений','yes');
INSERT INTO "module_action" VALUES (195,46,'notice-action','Действие по общесистемному уведомлению','yes');
INSERT INTO "module_action" VALUES (196,10,'comment','Комментарии к задачам проекта','yes');
INSERT INTO "module_action" VALUES (197,14,'img-gip-project-gantt','Проект закрепленные за ответственными','yes');
INSERT INTO "module_action" VALUES (198,14,'gip-project-gantt','Проекты по ответственным','yes');
INSERT INTO "module_action" VALUES (199,14,'department-gantt','Загрузка по подразделениям','yes');
INSERT INTO "module_action" VALUES (200,14,'img-deparment-gantt','График загрузки по подразделениям','yes');
INSERT INTO "module_action" VALUES (201,10,'set-today-me','Задачи поставленные сегодня мной','yes');
INSERT INTO "module_action" VALUES (202,2,'role','Управление ролями','yes');
INSERT INTO "module_action" VALUES (203,47,'view','Просмотр','yes');
INSERT INTO "module_action" VALUES (204,47,'delete','Удаление','yes');
INSERT INTO "module_action" VALUES (205,47,'edit','Редактировать','yes');




INSERT INTO "module_action" VALUES (349,47,'delete','Удалить сообщение','yes');
INSERT INTO "module_action" VALUES (350,47,'edit','Редактировать сообщение','yes');
INSERT INTO "module_action" VALUES (351,47,'report','Отчет по сообщениям','yes');
INSERT INTO "module_action" VALUES (352,47,'select-dls','Отчет по должностям','yes');
INSERT INTO "module_action" VALUES (353,47,'select-jrstate','Отчет по статусу','yes');
INSERT INTO "module_action" VALUES (354,47,'select-kio','Отчет по объектам','yes');
INSERT INTO "module_action" VALUES (355,47,'view','Просмотр','yes');
INSERT INTO "module_action" VALUES (377,48,'logs','Просмотр логов','yes');
INSERT INTO "module_action" VALUES (378,48,'rubrics','Просмотр рубрик','yes');
INSERT INTO "module_action" VALUES (379,48,'files','Просмотр файлов','yes');

INSERT INTO "module_action" VALUES (356,48,'delete','Удалить сообщение','yes');
INSERT INTO "module_action" VALUES (357,48,'edit','Редактировать сообщение','yes');
INSERT INTO "module_action" VALUES (358,48,'report','Отчет по сообщениям','yes');
INSERT INTO "module_action" VALUES (359,48,'select-dls','Отчет по должностям','yes');
INSERT INTO "module_action" VALUES (360,48,'select-jrstate','Отчет по статусу','yes');
INSERT INTO "module_action" VALUES (361,48,'select-kio','Отчет по объектам','yes');
INSERT INTO "module_action" VALUES (362,48,'view','Просмотр','yes');

INSERT INTO "module_action" VALUES (363,49,'delete','Удалить категорию (шаблон)','yes');
INSERT INTO "module_action" VALUES (364,49,'edit','Редактировать категорию(шаблон)','yes');
INSERT INTO "module_action" VALUES (365,49,'report','Отчет по категориям(шаблонам)','yes');
INSERT INTO "module_action" VALUES (369,49,'view','Просмотр','yes');


INSERT INTO "module_action" VALUES (370,50,'delete','Удалить рубрику','yes');
INSERT INTO "module_action" VALUES (371,50,'edit','Редактировать рубрику','yes');
INSERT INTO "module_action" VALUES (372,50,'report','Отчет по рубрикам','yes');
INSERT INTO "module_action" VALUES (376,50,'view','Просмотр','yes');



INSERT INTO "role_action" VALUES (2,1);
INSERT INTO "role_action" VALUES (2,11);
INSERT INTO "role_action" VALUES (2,14);
INSERT INTO "role_action" VALUES (2,17);
INSERT INTO "role_action" VALUES (2,26);
INSERT INTO "role_action" VALUES (2,28);
INSERT INTO "role_action" VALUES (2,29);
INSERT INTO "role_action" VALUES (2,31);
INSERT INTO "role_action" VALUES (2,35);
INSERT INTO "role_action" VALUES (2,37);
INSERT INTO "role_action" VALUES (2,44);
INSERT INTO "role_action" VALUES (2,46);
INSERT INTO "role_action" VALUES (2,54);
INSERT INTO "role_action" VALUES (2,55);
INSERT INTO "role_action" VALUES (2,56);
INSERT INTO "role_action" VALUES (2,57);
INSERT INTO "role_action" VALUES (2,58);
INSERT INTO "role_action" VALUES (2,59);
INSERT INTO "role_action" VALUES (2,75);
INSERT INTO "role_action" VALUES (2,78);
INSERT INTO "role_action" VALUES (2,174);
INSERT INTO "role_action" VALUES (2,178);
INSERT INTO "role_action" VALUES (2,179);
INSERT INTO "role_action" VALUES (2,180);
INSERT INTO "role_action" VALUES (2,181);
INSERT INTO "role_action" VALUES (2,182);
INSERT INTO "role_action" VALUES( 2,183);
INSERT INTO "role_action" VALUES (2,184);
INSERT INTO "role_action" VALUES (2,185);
INSERT INTO "role_action" VALUES (2,186);
INSERT INTO "role_action" VALUES (2,187);
INSERT INTO "role_action" VALUES (2,188);
INSERT INTO "role_action" VALUES (2,189);
INSERT INTO "role_action" VALUES (2,190);
INSERT INTO "role_action" VALUES (2,191);
INSERT INTO "role_action" VALUES (2,192); 
INSERT INTO "role_action" VALUES (2,193);
INSERT INTO "role_action" VALUES (2,196);
INSERT INTO "role_action" VALUES (2,201);
INSERT INTO "role_action" VALUES (3,1);
INSERT INTO "role_action" VALUES (3,4);
INSERT INTO "role_action" VALUES (3,6);
INSERT INTO "role_action" VALUES (3,7);
INSERT INTO "role_action" VALUES (3,9);
INSERT INTO "role_action" VALUES (3,11);
INSERT INTO "role_action" VALUES (3,13);
INSERT INTO "role_action" VALUES (3,14);
INSERT INTO "role_action" VALUES (3,17);
INSERT INTO "role_action" VALUES (3,19);
INSERT INTO "role_action" VALUES (3,26);
INSERT INTO "role_action" VALUES (3,28);
INSERT INTO "role_action" VALUES (3,29);
INSERT INTO "role_action" VALUES (3,31);
INSERT INTO "role_action" VALUES (3,35);
INSERT INTO "role_action" VALUES (3,37);
INSERT INTO "role_action" VALUES (3,44);
INSERT INTO "role_action" VALUES (3,46);
INSERT INTO "role_action" VALUES (3,47);
INSERT INTO "role_action" VALUES (3,48);
INSERT INTO "role_action" VALUES (3,49);
INSERT INTO "role_action" VALUES (3,54);
INSERT INTO "role_action" VALUES (3,55);
INSERT INTO "role_action" VALUES (3,56);
INSERT INTO "role_action" VALUES (3,57);
INSERT INTO "role_action" VALUES (3,58);
INSERT INTO "role_action" VALUES (3,59);
INSERT INTO "role_action" VALUES (3,74);
INSERT INTO "role_action" VALUES (3,75);
INSERT INTO "role_action" VALUES (3,77);
INSERT INTO "role_action" VALUES (3,78);
INSERT INTO "role_action" VALUES (3,79);
INSERT INTO "role_action" VALUES (3,80);

INSERT INTO "news_config" VALUES (1,11,101,'1209',1,1,20,10,1);
