\encoding win1251

begin;

select createTempTables();
select setCurrentDl(4);

select setAsNotLogging(1);
select setAsNotLogging(2);

\i ./functions/misc/f_safe_drop_trigger.sql
\i ./functions/misc/f_create_trigger.sql
\i ./functions/misc/f_is_table_exist.sql


--In readd_functions this calls does not invoked
--So, we should to invoke that here
\i ./functions/general/generateuid.sql
\i ./functions/io_objects/triggers/readd_triggers.sql
\i ./functions/categories/triggers/readd_triggers.sql
\i ./functions/inf_exchange/createtriggers.sql

\i ./functions/io_objects/checkioforowner.sql



select setAsLogging(1);
select setAsLogging(2);


\i ./functions/readd_functions.sql
\i ./functions/security/readd_security.sql

\i ./functions/tasks/zarya22/readd_zarya_func.sql

--alter table io_types rename to io_category_types; --сделается автоматически в триггере при апдейте таблицы io_objects
alter table io_categories rename id_io_type to id_io_category_type;
update attributes set code = 'id_io_category_type', table_name = 'io_category_types', name = 'Тип категории информационного объекта', title = 'Тип категории' where id = 10;
update io_categories set name = 'Типы категорий информационных объектов' where id = 3;
update io_categories set name = 'Справочник типов категорий информационных объектов' where id = 4;


--СЮДА (МЕЖДУ УДАЛЕНИЕМ И СОЗДАНИЕМ ТРИГГЕРА) ПОМЕЩАЕМ ЗАПРОСЫ НА СОЗДАНИЕ КАТЕГОРИЙ (ДОБАВЛЯТЬ СТРОКИ В ACCESS_CATEGORIES_TABLE НЕ НАДО)
select f_safe_drop_trigger('trgcheckcatforglobal', 'io_categories');

insert into io_categories (unique_id, id, id_io_category_type, id_child, is_main, name, code, description, is_system, is_global, id_io_state) values ('localorg-categories-17', 17, 10, NULL, false, 'Типы информационных объектов', 'SYSCATEGORY_17', NULL::varchar, true, true, 1);
insert into io_categories (unique_id, id, id_io_category_type, id_child, is_main, name, code, description, is_system, is_global, id_io_state) values ('localorg-categories-18', 18, 8, 17, true, 'Справочник типов информационных объектов', 'SYSCATEGORY_18', NULL::varchar, true, true, 1);
insert into io_categories (unique_id, id, id_io_category_type, id_child, is_main, name, code, description, is_system, is_global, id_io_state) values ('localorg-categories-19', 19, 10, NULL, false, 'Типы поисковых запросов', 'SYSCATEGORY_19', NULL::varchar, true, true, 1);
insert into io_categories (unique_id, id, id_io_category_type, id_child, is_main, name, code, description, is_system, is_global, id_io_state) values ('localorg-categories-20', 20, 8, 19, true, 'Справочник типов поисковых запросов', 'SYSCATEGORY_20', NULL::varchar, true, true, 1);

insert into io_life_cycle (id_io_category, id_state_src, id_state_dest) values (17, 1, 2);
insert into io_life_cycle (id_io_category, id_state_src, id_state_dest) values (17, 2, 1);
insert into io_life_cycle (id_io_category, id_state_src, id_state_dest) values (18, 1, 2);
insert into io_life_cycle (id_io_category, id_state_src, id_state_dest) values (18, 2, 1);
insert into io_life_cycle (id_io_category, id_state_src, id_state_dest) values (19, 1, 2);
insert into io_life_cycle (id_io_category, id_state_src, id_state_dest) values (19, 2, 1);
insert into io_life_cycle (id_io_category, id_state_src, id_state_dest) values (20, 1, 2);
insert into io_life_cycle (id_io_category, id_state_src, id_state_dest) values (20, 2, 1);

--таблица типов информационных объектов
insert into attrs_categories (id_io_category, id_io_attribute, def_value, is_mandatory, is_read_only) values (17, 1, NULL, true, true); --id
insert into attrs_categories (id_io_category, id_io_attribute, def_value, is_mandatory, is_read_only) values (17, 2, NULL, true, false); --name
insert into attrs_categories (id_io_category, id_io_attribute, def_value, is_mandatory, is_read_only) values (17, 3, NULL, false, false);  --description

--таблица типов поисковых запросов
insert into attrs_categories (id_io_category, id_io_attribute, def_value, is_mandatory, is_read_only) values (19, 1, NULL, true, true); --id
insert into attrs_categories (id_io_category, id_io_attribute, def_value, is_mandatory, is_read_only) values (19, 2, NULL, true, false); --name
insert into attrs_categories (id_io_category, id_io_attribute, def_value, is_mandatory, is_read_only) values (19, 27, NULL, false, false); --id_parent
insert into attrs_categories (id_io_category, id_io_attribute, def_value, is_mandatory, is_read_only) values (19, 3, NULL, false, false);  --description

select f_create_trigger('trgcheckcatforglobal', 'before', 'insert or update', 'io_categories', 'checkcatforglobal()');


--СЮДА (МЕЖДУ УДАЛЕНИЕМ И СОЗДАНИЕМ ТРИГГЕРОВ) ПОМЕЩАЕМ ЗАПРОСЫ НА СОЗДАНИЕ ИО (НАДО ДОБАВЛЯТЬ СТРОКИ В ACCESS_TABLE)
select f_safe_drop_trigger('trgioinsert', 'io_objects');
select f_safe_drop_trigger('zz_trgzioinserttableafter', 'io_objects');

update io_objects set table_name = 'io_category_types', name = 'Справочник типов категорий информационных объектов'  where id = 2;

insert into tbl_io_objects (unique_id, id, id_io_category, author, id_io_state, name, table_name, description, information, is_system, is_global, id_sync_type, insert_time, id_maclabel, id_owner_org)
values ('localorg-io_objects-9', 9, 18, 1, 1, 'Справочник типов информационных объектов', 'io_types', NULL, 'Системный объект', true, true, 5, current_timestamp, 1, NULL);
insert into access_table (id_io_object, id_role, allow_readlist, allow_read, allow_delete, allow_update)
values (9, -10, TRUE, TRUE, FALSE, TRUE); --Каждый пользователь должен иметь право редактирования записей справочника информационных объектов. Т.е. создавать, удалять и изменять информационные объекты

insert into tbl_io_objects (unique_id, id, id_io_category, author, id_io_state, name, table_name, description, information, is_system, is_global, id_sync_type, insert_time, id_maclabel, id_owner_org)
values ('localorg-io_objects-10', 10, 20, 1, 1, 'Справочник типов поисковых запросов', 'search_template_types', NULL, 'Системный объект', true, true, 5, current_timestamp, 1, NULL);
insert into access_table (id_io_object, id_role, allow_readlist, allow_read, allow_delete, allow_update)
values (10, -10, TRUE, TRUE, FALSE, FALSE);

--на этот раз триггеры вернем к жизни несколько позже, из-за необходимости апдейта Io_objects позднее

--select f_create_trigger('trgioinsert', 'before', 'insert or update', 'io_objects', 'ioinsertcheck()');
--select f_create_trigger('zz_trgzioinserttableafter', 'after', 'insert', 'io_objects', 'ioinsertchecktableafter()');


--ВСЕ ОСТАЛЬНОЕ ЗДЕСЬ

--почему-то иногда ряд атрибутов не обновляется.

--*****
update attributes set id_ref_attr_type = 9 where id_ref_attr_type isnull and column_name is not null;

--alter table indicator add column table_name varchar;
--alter table indicator add column column_name varchar;
alter table indicator add column id_ref_attr_type int4;
alter table indicator
   add constraint FK_INDICATOR_REF_A_TYPE foreign key (id_ref_attr_type)
      references a_types (id)
      on delete restrict on update restrict;

update indicator set id_ref_attr_type = (select id from atGetAttrType(column_name, table_name) limit 1) where id_ref_attr_type isnull and column_name is not null;
update indicator set id_ref_attr_type = 9 where id_ref_attr_type isnull and column_name is not null;
--******

create table io_types (
   id                   SERIAL               not null,
   name                 VARCHAR              not null,
   description          VARCHAR              null,
   constraint PK_IO_TYPES_TYPES primary key (id)
)
inherits (root_table);

select setMacToNULL('io_types');
select createTriggerUID('io_types');

insert into io_types (id, name, description) values(1, 'Общие документы', NULL);
insert into io_types (id, name, description) values(2, 'Общие справочники', NULL);
insert into io_types (id, name, description) values(3, 'Системные справочники', NULL);
SELECT pg_catalog.setval('io_types_id_seq', 3, true);

create table search_template_types (
   id                   SERIAL               not null,
   id_parent            INT4                 null,
   name                 VARCHAR              not null,
   description          VARCHAR              null,
   constraint PK_SEARCH_TEMPLATE_TYPES primary key (id)
)
inherits (root_table);

comment on table search_template_types is
'Типы поисковых запросов
Справочник введен для возможности типизации и рубрикации списка поисковых запросов с целью удобства их отображения для пользователя';

select setMacToNULL('search_template_types');
select createTriggerUID('search_template_types');

alter table search_template_types
   add constraint FK_SEARCH_T_PARENT_SEARCH_T foreign key (id_parent)
      references search_template_types (id)
      on delete restrict on update restrict;

insert into search_template_types (id, name, description) values(1, 'Общие поисковые запросы', NULL);
SELECT pg_catalog.setval('search_template_types_id_seq', 1, true);


insert into attributes (unique_id, id, id_a_type, code, name, title, table_name, column_name, def_width, is_system) values('localorg-attributes-43', 43, 2, 'id_io_type', 'Тип информационного объекта', 'Тип ИО', 'io_types', 'name', 150, TRUE);
insert into attrs_categories (id_io_category, id_io_attribute, def_value, is_mandatory, is_read_only) values (13, 43, '1', true, false);  --id_io_type

alter table tbl_io_objects add column id_io_type int4;
alter table tbl_io_objects
   add constraint FK_IO_OBJECT_TYPE_REF foreign key (id_io_type)
      references io_types (id)
      on delete restrict on update restrict;

update tbl_io_objects set id_io_type = 1;


alter table tbl_io_objects alter column id_io_type set not null;
alter table tbl_io_objects alter column id_io_type set default 1;

--чтобы перегенерился тип возвращаемых данных для tbl_io_objects
\i ./functions/security/ctrl/acl_secure_io_objects.sql 

insert into attributes (unique_id, id, id_a_type, code, name, title, table_name, column_name, def_width, is_system) values('localorg-attributes-53', 53, 2, 'id_search_template_type', 'Тип поискового запроса', 'Тип поискового запроса', 'search_template_types', 'name', 150, TRUE);
insert into attrs_categories (id_io_category, id_io_attribute, def_value, is_mandatory, is_read_only) values (73, 53, '1', true, false);  --id_search_template_type

alter table search_templates add column id_search_template_type int4;
alter table search_templates
   add constraint FK_SEARCH_TEMPLATES_TYPE_REF foreign key (id_search_template_type)
      references search_templates (id)
      on delete restrict on update restrict;

update search_templates set id_search_template_type = 1;

alter table search_templates alter column id_search_template_type set not null;
alter table search_templates alter column id_search_template_type set default 1;

update io_categories set name = 'Поисковые запросы' where id = 73;
update io_categories set name = 'Справочник поисковых запросов' where id = 74;
update tbl_io_objects set name = 'Справочник поисковых запросов (фильтров)' where id = 36;

--в обычном случае данные вызовы должны быть выше
select f_create_trigger('trgioinsert', 'before', 'insert or update', 'io_objects', 'ioinsertcheck()');
select f_create_trigger('zz_trgzioinserttableafter', 'after', 'insert', 'io_objects', 'ioinsertchecktableafter()');


select setGrantsEx(NULL);

create or replace view io_objects as select * from f_sel_io_objects(NULL);
revoke all on tbl_io_objects from public;
grant all on io_objects to public;

create or replace rule "r_ins_io_objects" as on insert to "io_objects" do instead 
select "f_ins_io_objects" (new."unique_id", 
                           new."last_update", 
                           new."id", 
                           new."id_io_category", 
                           new."id_io_state", 
                           new."id_maclabel", 
                           new."author", 
                           new."id_sync_type", 
                           new."id_owner_org", 
                           new."name", 
                           new."table_name", 
                           new."description", 
                           new."information", 
                           new."is_system", 
                           new."insert_time", 
                           new."is_completed", 
                           new."is_global", 
                           new."record_fill_color", 
                           new."record_text_color", 
                           new."id_search_template", 
                           new."ref_table_name",
                           new."id_io_type");


create or replace rule "r_upd_io_objects" as on update to "io_objects" do instead 
select "f_upd_io_objects" (new."unique_id", 
                           new."last_update", 
                           new."id", 
                           new."id_io_category", 
                           new."id_io_state", 
                           new."id_maclabel", 
                           new."author", 
                           new."id_sync_type", 
                           new."id_owner_org", 
                           new."name", 
                           new."table_name", 
                           new."description", 
                           new."information", 
                           new."is_system", 
                           new."insert_time", 
                           new."is_completed", 
                           new."is_global", 
                           new."record_fill_color", 
                           new."record_text_color", 
                           new."id_search_template", 
                           new."ref_table_name",
                           new."id_io_type");

--добавление атрибута id_io_type в шаблон ИО
insert into io_views (id_io_category, id_io_attribute, id_io_template, id_a_group, is_read_only, "order", def_value) values(13, 43, 1, 1, false, 3, '1');--id_io_type


update attrs_categories set def_value = 
'/* XPM */
static char *dummy[]={
"128 128 1075 2",
"Qt c None",
"iE c #066da7",
"dO c #076da7",
"dN c #086aa4",
"if c #086ea8",
"dE c #0870a8",
"hU c #0870a9",
"du c #0871a9",
"dD c #096da5",
"aU c #0971ab",
"iF c #0a6aa1",
"dt c #0a70a7",
"dj c #0a71a8",
"dk c #0a73ab",
"db c #0b74ac",
"dW c #0c689e",
"da c #0c73a9",
"aN c #0c76ad",
"eF c #0d72a7",
"c2 c #0d74aa",
"gO c #0d77ad",
"cT c #0d77ae",
"cS c #0e76ab",
"gq c #0e79ae",
"cJ c #0e79af",
"aC c #0e7aaf",
"hb c #0f72a5",
"cI c #0f77ac",
"cB c #1079ad",
"cC c #107ab1",
"ct c #117db1",
"aD c #117db2",
"eY c #1272a3",
"cs c #127aaf",
"aB c #127db2",
"au c #127fb2",
"fP c #1379ad",
"ck c #137daf",
"cl c #137fb2",
"aM c #137fb3",
"hw c #146f9f",
"cc c #1480b3",
"fQ c #157cae",
"cb c #157fb0",
"b5 c #1581b4",
"d8 c #166d96",
"b4 c #1680b1",
"ak c #1683b6",
"bW c #1781b2",
"eZ c #1783b6",
"bX c #1784b6",
"f7 c #1878a7",
"bO c #1886b7",
"aT c #1886b8",
"f6 c #1979a7",
"fg c #198398",
"e0 c #1983a9",
"bN c #1984b4",
"eG c #1986b2",
"bF c #1a86b5",
"ac c #1a87b8",
"ha c #1b81af",
"bx c #1c87b6",
"by c #1c88b9",
"ff c #1d7299",
"fy c #1d8588",
"d9 c #1d8aba",
"bs c #1e88b7",
"#6 c #1f8bba",
"dX c #1f8dbb",
"mY c #20480b",
"hV c #20698f",
"bn c #218bb8",
"bo c #218dbb",
"#5 c #218ebb",
"#7 c #218ebc",
"bl c #218ebe",
"dY c #228eb1",
"hv c #2380aa",
"e. c #238ca1",
"bk c #238db9",
"bg c #238ebc",
"dP c #238ebe",
"#X c #238fbe",
"em c #246d8c",
"dQ c #2490b5",
"bh c #2491be",
"iD c #2589b4",
"aj c #2591be",
"al c #2592be",
"mu c #265110",
"ni c #265b0c",
"en c #268d92",
"bd c #2691bc",
"be c #2692c0",
"gr c #277498",
"gp c #277699",
"dv c #2793c0",
"dF c #2794b6",
"ba c #2892be",
"#O c #2893c0",
"bb c #2893c1",
"l2 c #2a5313",
"mQ c #2a600f",
"a9 c #2a93bf",
"dl c #2a95c2",
"dw c #2a96b7",
"b. c #2a96c2",
"av c #2a97c2",
"dV c #2c5b77",
"nc c #2c6e0d",
"fx c #2c6e8b",
"nw c #2c760b",
"eH c #2c937e",
"a6 c #2c96c0",
"at c #2c97c2",
"a7 c #2d97c3",
"dm c #2d99ba",
"#F c #2e97c3",
"a3 c #2f97c1",
"a4 c #2f99c4",
"ml c #306613",
"hT c #30799b",
"m8 c #307b0e",
"c3 c #309ac4",
"dc c #309bbb",
"nr c #31870c",
"aY c #3199c2",
"aZ c #319bc5",
"np c #31ac05",
"mK c #327311",
"nq c #32a706",
"nh c #33910c",
"aQ c #339bc3",
"#E c #339bc5",
"#w c #339dc6",
"ig c #34637e",
"nb c #349a0a",
"#N c #349dc5",
"aE c #349dc6",
"c4 c #349ebd",
"#v c #349ec7",
"ng c #34ad06",
"#G c #359dc6",
"#x c #359ec7",
"na c #35ae07",
"lU c #366d18",
"gN c #366f89",
"mX c #368b0f",
"e1 c #369b6d",
"aI c #369dc4",
"cU c #369fbe",
"m7 c #36a70a",
"eE c #376b7e",
"mC c #378213",
"aJ c #379fc7",
"aA c #379fc9",
"md c #387c16",
"#P c #389fc7",
"#W c #389fc9",
"m6 c #38b108",
"ax c #399fc5",
"#o c #39a0c9",
"cK c #39a2c0",
"gP c #3a7087",
"mP c #3a960f",
"fR c #3b9986",
"aq c #3ba0c7",
"mW c #3bae0a",
"mt c #3c9114",
"ar c #3ca2c9",
"cu c #3ca3cb",
"mV c #3cb30a",
"mJ c #3da20f",
"#Y c #3da3cb",
"cD c #3da4c1",
"lN c #3e811a",
"af c #3ea1c7",
"ag c #3ea4cc",
"mO c #3eb40b",
"fO c #3f6a7c",
"ie c #3f708a",
"l9 c #3f8a17",
"#g c #3fa4cc",
"cv c #3fa6c3",
"mI c #3fb60c",
"a. c #40a3ca",
"a# c #41a5cd",
"mB c #41af0f",
"mk c #429e14",
"fh c #42a65f",
"cd c #42a7cd",
"mA c #42b70d",
"#2 c #43a4cb",
"cm c #43a7c5",
"aL c #43a7ce",
"#3 c #43a8ce",
"l1 c #449718",
"ms c #44b60f",
"#S c #45a7cc",
"#n c #45a8ce",
"aV c #45a8cf",
"mr c #45b90e",
"h# c #46687a",
"#f c #46a8cf",
".8 c #46a9cf",
"mc c #46aa14",
"dZ c #46ac77",
"ce c #47aac6",
"ab c #47abd0",
"mj c #47ba10",
"#L c #48a8cd",
"lF c #49981e",
".7 c #49abd0",
"lT c #4aa619",
"mb c #4abc11",
"eX c #4b696e",
"#B c #4ba9ce",
"b6 c #4bacc8",
"l8 c #4bb714",
"#C c #4cadd0",
"e# c #4dad6b",
".W c #4dadd0",
".9 c #4daed2",
"l7 c #4dbe12",
"#s c #4eabce",
"bY c #4eadc9",
".X c #4eaed2",
"lM c #4eb119",
"iG c #4f5e6c",
"iC c #4f6675",
"l0 c #4fbd14",
"#k c #50acd0",
"bG c #50afd3",
"lZ c #50c014",
"f5 c #51656b",
"aS c #51afd4",
"#l c #51b1d3",
"hc c #526b79",
"bP c #52b0ca",
"#c c #53afd1",
"ai c #53b1d4",
"lS c #53c216",
".Q c #54b1d4",
"bH c #54b2cd",
".V c #54b2d4",
".6 c #54b2d5",
"fz c #54b451",
"lE c #54bd1b",
"lL c #54c317",
"am c #55b3d5",
".2 c #56b0d2",
".P c #57b2d5",
".3 c #57b3d5",
"lD c #57c41a",
"#y c #58b4d7",
"dR c #58c11b",
"lz c #58c11d",
"oU c #59130a",
"oy c #59180b",
".T c #59b1d3",
"bz c #59b4ce",
"hu c #5a6065",
"d7 c #5a6a67",
".N c #5ab6d7",
"ly c #5ac61c",
"ot c #5b1c0f",
".O c #5bb1d2",
".U c #5bb4d5",
"bp c #5bb6d7",
".M c #5cb4d5",
"bt c #5cb6cf",
"lt c #5cc51e",
"oO c #5d2012",
".4 c #5db7d7",
"ls c #5dc91c",
".5 c #5eb8d7",
"eo c #5ebb5e",
"dG c #5ec61f",
"nQ c #5f140b",
"fe c #5f6561",
"o# c #60190d",
"bm c #60b6d5",
"bq c #60b8d0",
"#V c #60b8d7",
"#H c #60b8d9",
"#d c #60b9d9",
"ll c #60c620",
"dH c #60c91f",
".L c #61afce",
".K c #61b9d9",
"bi c #63b9da",
"#u c #63bad9",
"#e c #63bada",
"lg c #63c923",
"lf c #63cb21",
"of c #641d10",
"bj c #64b7d8",
"dx c #64cb21",
"nW c #652312",
".J c #65b4d3",
"#m c #65bbda",
"a1 c #65bcdb",
"la c #65cb23",
"dy c #65cd21",
"go c #666059",
"bf c #66b9d8",
"bc c #68bcd9",
".H c #68bcdb",
"#t c #68bedb",
"k7 c #68cd26",
"k6 c #68cf24",
"hS c #695956",
".I c #69afcd",
".G c #6abad9",
".R c #6abedb",
"dn c #6acf25",
"do c #6ad025",
"#D c #6bbedc",
"fS c #6bc54b",
"kZ c #6bce28",
"dp c #6bd026",
"i1 c #6c575a",
".F c #6db4d2",
"b# c #6dbcda",
"aF c #6dbedc",
"dz c #6dd026",
"#M c #6ec0dd",
"kS c #6ed029",
"kR c #6ed227",
"dI c #6ed228",
"a8 c #70bfdc",
".Y c #70c1dd",
".E c #70c1de",
"dd c #70d228",
"de c #70d328",
"hx c #716664",
"#T c #71c2de",
"az c #71c2df",
"kN c #71d12b",
"kM c #71d329",
"el c #726858",
"i0 c #736164",
"f8 c #737673",
".D c #73bbd8",
"#Z c #73c3df",
"dS c #73d42c",
"oN c #741a0c",
".C c #74b5d2",
"a5 c #74c1dd",
"#U c #74c3df",
"#. c #74c3e0",
"kG c #74d32f",
"c5 c #74d42e",
"kF c #74d52d",
"c6 c #74d52e",
".A c #76c0dc",
".B c #76c4e0",
"eI c #76cb55",
"a2 c #77c2de",
"#4 c #77c4e0",
"aW c #77c5e1",
"ky c #77d331",
"kx c #77d52f",
"os c #781f10",
"fw c #78604e",
".z c #78bad6",
"n6 c #791e0e",
"oo c #792311",
"gM c #795746",
"oI c #7a2815",
"aX c #7ac4e0",
"aa c #7ac6e2",
"kk c #7ad732",
"cV c #7ad831",
"kj c #7ad930",
"cW c #7ad931",
"#h c #7cc6e2",
"nK c #7d180c",
"o. c #7d2613",
"id c #7d4c3f",
".w c #7dc0db",
".x c #7dc5e0",
".y c #7dc7e2",
"j7 c #7dd835",
"j6 c #7dda33",
"aP c #7fc7e0",
"ah c #7fc7e2",
"aO c #7fc9e2",
"cL c #7fd935",
"as c #80c9e3",
"cA c #80d242",
"jU c #80d837",
"cM c #80da35",
"cX c #80db37",
"aH c #81c7e1",
"aG c #81c9e3",
"aK c #81c9e4",
"jK c #81d93a",
"cN c #81db37",
"c7 c #81db38",
".t c #82c0da",
".u c #83c6df",
".v c #83cbe4",
"cE c #83dc39",
"aw c #84cae2",
"#p c #84cce4",
"ay c #84cce5",
"cr c #84d447",
"jw c #84db3c",
"cz c #84dc3a",
"df c #84dd38",
"cF c #84dd39",
"jv c #84dd3a",
"nP c #862e17",
"an c #86cce5",
"ap c #87cbe4",
"ao c #87cde6",
"cq c #87dc3e",
"jk c #87dd3e",
"jj c #87df3c",
".q c #88c5de",
"cj c #88d64b",
"e2 c #88d951",
"cy c #88df3c",
"fN c #895d3f",
"hW c #896156",
"cw c #89df3d",
"eD c #8a6748",
".r c #8acce4",
".s c #8acee6",
"#z c #8acee7",
"aR c #8acfe7",
"ca c #8ad84f",
"cx c #8ae03d",
"ae c #8bcde5",
"ad c #8bcfe7",
"i6 c #8bde40",
"ci c #8bdf40",
"i5 c #8be03e",
"cp c #8be13e",
"h. c #8c4e35",
".n c #8cc4de",
"iB c #8d422c",
".o c #8dcae2",
"a0 c #8dd0e7",
"iM c #8de043",
"cn c #8de141",
"iL c #8de241",
"oH c #8e1e0f",
"ok c #8e2712",
"#9 c #8ecee5",
"#8 c #8ed0e7",
"b3 c #8eda52",
"c# c #8edf46",
"co c #8ee241",
"on c #8f2511",
".p c #8fd0e8",
"im c #8fe044",
"ch c #8fe242",
"nD c #90190c",
"n1 c #90210f",
"b2 c #90e048",
".k c #91cae2",
".S c #91cfe5",
"#1 c #91d0e6",
"#0 c #91d2e8",
"#I c #91d2e9",
"oD c #922f17",
"gs c #927462",
"bV c #92db55",
"h2 c #92e245",
"cf c #92e345",
"h1 c #92e443",
"c. c #92e445",
".l c #93d1e7",
"#R c #93d1e8",
"#Q c #93d3ea",
"cg c #93e445",
".m c #95d4ea",
"bU c #95e14d",
"hD c #95e348",
"hC c #95e546",
"cG c #95e547",
"n5 c #962d16",
"#K c #96d3e8",
"#J c #96d5ea",
"dJ c #96e547",
"b1 c #96e647",
".h c #97cfe5",
"hi c #97e54b",
"b9 c #97e749",
"bM c #98e352",
"b7 c #98e649",
".e c #99cee5",
".Z c #99d3e9",
"#A c #99d5eb",
"fi c #99e551",
"b8 c #99e749",
"ht c #9a4827",
".i c #9ad6eb",
".j c #9ad7eb",
"gV c #9ae54c",
"bT c #9ae74a",
"cO c #9ae74c",
"eW c #9b653c",
"#r c #9bd5ea",
"#q c #9bd7ec",
"b0 c #9be84c",
"oC c #9c220f",
"nJ c #9c341b",
"f4 c #9c5731",
".f c #9cd4e9",
"bE c #9ce557",
"bZ c #9ce84d",
"## c #9dd7ec",
"gx c #9de74f",
"dT c #9de84e",
"bL c #9de94d",
"cY c #9de94e",
"#j c #9ed7eb",
"#i c #9ed9ed",
"ga c #9ee852",
"bS c #9ee94e",
"g# c #9eea50",
"oW c #9f1b0d",
"iZ c #9f3b1d",
".b c #9fd3e8",
".g c #9fd9ed",
"bw c #9fe55b",
"bQ c #9fe951",
"bD c #9fea50",
"nX c #a0200e",
"og c #a02712",
"oz c #a02f16",
".# c #a0d3e8",
"#b c #a0d8ec",
"#a c #a0daee",
"ea c #a0e75b",
"br c #a0e75f",
"fT c #a0e853",
"bR c #a0ea51",
"c8 c #a0eb54",
"d0 c #a1eb54",
"oj c #a22913",
".c c #a2d9ec",
".1 c #a2d9ed",
"bK c #a2ea51",
".a c #a3d8eb",
".0 c #a3dbee",
"fB c #a3e956",
"fA c #a3eb54",
"bC c #a3ec54",
".d c #a4dbee",
"bv c #a4eb54",
"bI c #a4eb55",
"fk c #a5eb59",
"bJ c #a5ec55",
"fj c #a5ed57",
"n0 c #a63218",
"hR c #a6421c",
"bu c #a6ec58",
"e3 c #a6ed5a",
"gn c #a75328",
"bA c #a7ed5a",
"dg c #a7ee57",
"bB c #a7ee58",
"nx c #a81a0b",
"oT c #a81b0c",
"oV c #a8381c",
"ep c #a8ee5b",
"eK c #a8ee5d",
"fd c #a96233",
"d6 c #a96e3f",
"eJ c #a9ef5b",
"ic c #aa3e18",
"er c #aaef60",
"dq c #abef5d",
"ec c #abf061",
"iA c #ac3b16",
"ih c #ac5f45",
"eq c #acf05e",
"gL c #ad4f23",
"eb c #adf160",
"d2 c #adf263",
"nR c #ae1f0d",
"ox c #ae250f",
"oa c #af2910",
"dA c #aff163",
"d1 c #aff263",
"iY c #b03914",
"g9 c #b04b21",
"gQ c #b07153",
"cH c #b0f066",
"dU c #b0f264",
"ou c #b12f15",
"oP c #b13819",
"nC c #b1391b",
"oe c #b22e14",
"fv c #b25e2e",
"dK c #b2f264",
"dM c #b2f367",
"hs c #b34a1e",
"fM c #b35d2b",
"ek c #b46e3b",
"cP c #b4f265",
"dL c #b4f367",
"dC c #b4f468",
"ds c #b5f56a",
"oM c #b61f0c",
"nV c #b63718",
"hQ c #b6471c",
"f3 c #b65b2a",
"eC c #b66d39",
"dB c #b6f468",
"dr c #b7f56a",
"di c #b7f66b",
"cZ c #b8f56a",
"c9 c #b8f66d",
"d# c #b8f66e",
"ib c #b9431a",
"gm c #b95828",
"eV c #b96c36",
"dh c #b9f66b",
"d. c #baf66e",
"c1 c #baf770",
"nL c #bb1c0b",
"or c #bb2710",
"iz c #bb4018",
"d5 c #bb683c",
"cR c #bbf670",
"n7 c #bc2610",
"gK c #bc5626",
"fc c #bc6934",
"c0 c #bcf770",
"op c #bd2f14",
"oJ c #be3818",
"iX c #be3d16",
"cQ c #bef771",
"g8 c #bf5224",
"n9 c #c03114",
"fu c #c06631",
"hr c #c25020",
"fL c #c3652f",
"ej c #c37740",
"nE c #c5190a",
"oG c #c5200b",
"hP c #c54d1f",
"eB c #c5763e",
"n2 c #c6240d",
"nO c #c63b18",
"iH c #c6603a",
"d4 c #c6603d",
"f2 c #c6632e",
"ia c #c7481c",
"om c #c82a10",
"ol c #c82e11",
"d3 c #c86146",
"eU c #c8753b",
"iy c #c94519",
"gl c #c9602b",
"oE c #cb3817",
"iW c #cb4117",
"gJ c #cb5c29",
"fb c #cb7238",
"n4 c #cc3514",
"hd c #cc7146",
"g7 c #ce5827",
"ny c #cf1707",
"oB c #cf210b",
"ft c #cf6e35",
"nI c #d03f1a",
"hq c #d05623",
"nY c #d1210b",
"ns c #d21708",
"oS c #d21807",
"hO c #d25221",
"fK c #d26d33",
"ei c #d28145",
"nj c #d41808",
"nd c #d41b09",
"oh c #d42c0f",
"i# c #d44d1e",
"f1 c #d46a31",
"nS c #d51f09",
"ow c #d5220a",
"oA c #d53814",
"ix c #d5481b",
"eA c #d57f42",
"iV c #d64518",
"nt c #d71706",
"oR c #d71806",
"nk c #d71a07",
"m9 c #d71e0a",
"jd c #d73f16",
"gk c #d7662e",
"eT c #d77e3f",
"mZ c #d8210a",
"mR c #d8230a",
"mL c #d8250c",
"mD c #d8270d",
"ob c #d8290c",
"nZ c #d83814",
"gI c #d8622b",
"oL c #d91c07",
"ne c #d91c08",
"mv c #d92a0e",
"je c #d93f16",
"g6 c #d95d29",
"es c #d96246",
"fa c #d97a3c",
"oF c #da1d08",
"n. c #da1f08",
"kr c #da2108",
"mS c #da230a",
"mM c #da250b",
"mm c #da2c0f",
"od c #da2f0e",
"ov c #da3511",
"eL c #da6142",
"ed c #da6549",
"kd c #db260b",
"m0 c #db280b",
"mE c #db280c",
"me c #db2e0f",
"hp c #db5a25",
"e4 c #db6040",
"nM c #dc290c",
"mF c #dc290d",
"mw c #dc2a0d",
"j2 c #dc2c0d",
"m. c #dc3110",
"l3 c #dc3212",
"oQ c #dc4017",
"iU c #dc4719",
"hN c #dc5522",
"fs c #dc7539",
"mn c #dd2c0d",
"nF c #dd2e0e",
"j1 c #dd2f0e",
"lV c #dd3613",
"lO c #dd3a14",
"nU c #dd3b14",
"jc c #dd4016",
"nB c #dd4319",
"iw c #dd4b1c",
"i. c #dd5020",
"fl c #dd623c",
"i2 c #dd6432",
"ke c #de2e0e",
"mf c #de2f0e",
"kc c #de2f10",
"jS c #de3010",
"n8 c #de3110",
"lG c #de3c15",
"nv c #de4a1b",
"no c #de521b",
"fC c #de6038",
"fJ c #de7336",
"hy c #de763f",
"oc c #df3110",
"nl c #df3410",
"l4 c #df3411",
"n3 c #df3511",
"nm c #df3512",
"jE c #df3812",
"lA c #df3e16",
"nf c #df551d",
"f0 c #df7034",
"ks c #e03311",
"lW c #e03913",
"lP c #e03a13",
"lu c #e04017",
"jb c #e04117",
"lm c #e04318",
"lh c #e0451a",
"iT c #e0481a",
"n# c #e0581f",
"eh c #e08949",
"kq c #e13713",
"oi c #e13a13",
"mg c #e13c13",
"lH c #e13c14",
"jr c #e13d14",
"nz c #e13d15",
"mG c #e13e15",
"ja c #e14217",
"jf c #e14518",
"lb c #e1471c",
"iv c #e14d1d",
"m5 c #e15b20",
"gH c #e1662d",
"gj c #e16b30",
"ez c #e18646",
"lB c #e23e15",
"oK c #e23f15",
"mx c #e23f16",
"lv c #e24116",
"nH c #e24117",
"j# c #e24217",
"lI c #e24218",
"ln c #e24318",
"jq c #e24518",
"iS c #e2491a",
"k8 c #e24b1c",
"k0 c #e24e1e",
"h9 c #e25220",
"ho c #e25d26",
"mU c #e25e22",
"g5 c #e2602a",
"mN c #e26125",
"f9 c #e2874c",
"nA c #e34318",
"j. c #e34518",
"li c #e3451a",
"nu c #e3471a",
"iR c #e3491a",
"jD c #e3491c",
"iu c #e34d1d",
"kT c #e3501f",
"hM c #e35823",
"eS c #e38443",
"lc c #e4491a",
"jF c #e4491c",
"mT c #e44a1c",
"k9 c #e44c1c",
"nG c #e44d1c",
"kO c #e45321",
"mH c #e46427",
"mz c #e46528",
"f# c #e4803f",
"l5 c #e54d1d",
"it c #e54e1d",
"oq c #e54e1f",
"h8 c #e55321",
"kH c #e55623",
"kz c #e55723",
"hL c #e55924",
"kl c #e55a26",
"mq c #e5692a",
"mi c #e56c2c",
"ee c #e56d43",
"jR c #e64e1f",
"lo c #e6501f",
"kU c #e6511f",
"mh c #e6531f",
"k1 c #e65321",
"h7 c #e65421",
"j8 c #e65d27",
"hn c #e65f27",
"g4 c #e6622b",
"gG c #e6692e",
"gi c #e66e32",
"fI c #e67738",
"h6 c #e75421",
"kI c #e75521",
"m1 c #e75723",
"j3 c #e75725",
"lp c #e75823",
"kA c #e75824",
"hK c #e75a24",
"is c #e75a25",
"jV c #e76029",
"jL c #e7612a",
"ma c #e76f2e",
"l6 c #e77230",
"fZ c #e77335",
"fr c #e77a3b",
"hJ c #e85a24",
"mo c #e85a25",
"j0 c #e85a27",
"hI c #e85b25",
"lX c #e85d26",
"l. c #e85e26",
"iQ c #e85e27",
"hm c #e86027",
"jx c #e8632b",
"g3 c #e8632c",
"jl c #e8652e",
"et c #e86e40",
"lY c #e87632",
"lR c #e87935",
"km c #e95e26",
"j9 c #e95e27",
"hl c #e96027",
"jW c #e96028",
"nT c #e96128",
"nn c #e96129",
"i7 c #e9682f",
"gF c #e96a2f",
"iN c #e96b31",
"eM c #e9703f",
"ey c #e98b49",
"kf c #ea5e29",
"ld c #ea6129",
"jM c #ea6329",
"nN c #ea632a",
"i9 c #ea642a",
"g2 c #ea642c",
"jy c #ea652c",
"m2 c #ea672c",
"lj c #ea672d",
"gE c #ea6b2f",
"in c #ea6d32",
"gh c #ea7032",
"e5 c #ea703c",
"lK c #ea7c36",
"lC c #ea7f38",
"lx c #ea823b",
"f. c #ea8341",
"eR c #ea8945",
"eg c #ea904d",
"kb c #eb642d",
"jX c #eb672d",
"kt c #eb672f",
"jm c #eb682d",
"m3 c #eb682e",
"kB c #eb6a2e",
"g1 c #eb6a2f",
"gD c #eb6b2f",
"h3 c #eb7035",
"fD c #eb7138",
"fm c #eb7139",
"hE c #eb7336",
"fY c #eb7636",
"fH c #eb7a39",
"lr c #eb853d",
"my c #ec6b2f",
"mp c #ec6d2f",
"iO c #ec6d30",
"jp c #ec6d31",
"gC c #ec6e30",
"m# c #ec6e31",
"k. c #ec7031",
"gg c #ec7133",
"hj c #ec7637",
"fq c #ec7d3d",
"fU c #ec7f41",
"lk c #ec883f",
"le c #ec8b41",
"hH c #ed6e31",
"jn c #ed7031",
"io c #ed7033",
"gf c #ed7133",
"lw c #ed7333",
"h4 c #ed7334",
"m4 c #ed7435",
"fX c #ed7737",
"gW c #ed793a",
"fG c #ed7b3a",
"ef c #ed8548",
"gt c #ed8e4b",
"js c #ee7134",
"kp c #ee7335",
"lq c #ee7435",
"kD c #ee7438",
"hF c #ee7635",
"fW c #ee7737",
"jC c #ee7738",
"k2 c #ee7937",
"ge c #ee7938",
"ir c #ee7939",
"fV c #ee793b",
"gy c #ee7a3b",
"fF c #ee7c3a",
"hX c #ee7d3d",
"e9 c #ee8542",
"l# c #ee8d44",
"ex c #ee8e4b",
"kJ c #ef7939",
"jG c #ef793a",
"gX c #ef7a39",
"g0 c #ef7a3a",
"fE c #ef7c3a",
"gz c #ef7d3c",
"gb c #ef7d3e",
"fp c #ef7f3e",
"eQ c #ef8b46",
"k5 c #ef9045",
"kY c #ef9348",
"kQ c #ef954b",
"lQ c #f07f3c",
"gd c #f07f3d",
"fo c #f07f3e",
"gc c #f0803d",
"jz c #f0803e",
"gB c #f0813f",
"e8 c #f08643",
"kL c #f0974c",
"g. c #f0ac60",
"fn c #f1803e",
"gA c #f1813f",
"ii c #f1833f",
"gY c #f18341",
"jQ c #f18342",
"gZ c #f18441",
"kC c #f18442",
"e6 c #f18642",
"e7 c #f18743",
"eu c #f18747",
"eN c #f18846",
"eP c #f18c47",
"ew c #f1904b",
"kE c #f19a4f",
"kw c #f19b52",
"k3 c #f28743",
"jN c #f28843",
"hk c #f28845",
"lJ c #f28a45",
"h5 c #f28a46",
"hG c #f28b46",
"j4 c #f28b47",
"eO c #f28d47",
"kX c #f28e49",
"iq c #f28f4a",
"ki c #f29e53",
"kK c #f38e49",
"ip c #f38e4a",
"jZ c #f38e4c",
"ev c #f3914c",
"gR c #f3924c",
"kg c #f3924d",
"j5 c #f3a256",
"jo c #f4924d",
"iP c #f4934d",
"kV c #f4954e",
"ku c #f49550",
"jT c #f4a359",
"jJ c #f4a55a",
"i8 c #f59650",
"he c #f59651",
"jg c #f59750",
"kv c #f59753",
"jA c #f59953",
"jB c #f59954",
"kh c #f59a54",
"kW c #f59b54",
"jO c #f59b55",
"ju c #f5a85c",
"ji c #f5aa5e",
"i4 c #f5ab61",
"ka c #f69b55",
"hz c #f69d55",
"kP c #f69d57",
"jP c #f69e57",
"jY c #f69f58",
"jH c #f69f5a",
"k4 c #f6a05a",
"iK c #f6ad62",
"il c #f6b064",
"hY c #f7a05a",
"k# c #f7a05b",
"ko c #f7a25a",
"jI c #f7a25b",
"kn c #f7a35d",
"jt c #f7a45d",
"jh c #f7a75e",
"ij c #f7a760",
"h0 c #f7b166",
"iI c #f8a860",
"i3 c #f8a861",
"gu c #f8ab64",
"hB c #f8b369",
"hh c #f8b46a",
"iJ c #f9ab63",
"ik c #f9ad65",
"gU c #f9b76c",
"gw c #f9b76d",
"hZ c #faae67",
"gS c #faaf67",
"hf c #faaf69",
"hA c #fab16a",
"hg c #fab26b",
"gT c #fbb46d",
"gv c #fbb670",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.#.a.a.#QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.b.c.d.d.d.d.c.bQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.e.f.g.g.g.g.g.g.g.g.g.g.f.eQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.h.i.j.j.j.j.j.j.j.j.j.j.j.j.j.j.i.hQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.k.l.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.m.l.kQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.n.o.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.p.o.nQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.q.r.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.r.qQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.t.u.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.u.tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.w.x.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.x.wQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.z.A.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.A.zQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.C.D.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.D.CQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.F.G.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.G.FQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.I.J.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.K.J.IQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.L.M.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.M.LQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.O.P.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.R.SQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.T.N.U.V.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.X.Y.Z.0.1QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.2.3.N.4.5.6.7.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.9#.###a#a#a#bQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#c.V.3.N.4#d#e.3#f#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g.X#h###i#i#i#i#i#jQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#k#l.V.3.N.4#d#e#m.4#n#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#l#p#q#q#q#q#q#q#q#q#rQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#s.X#l.V.3.N.4#d#e#m#t#u.7#v#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#x#y#z#A#A#A#A#A#A#A#A#A#A.ZQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#B#C.X#l.V.3.N.4#d#e#m#t#D.R.W#E#F#F#F#F#F#F#F#F#F#F#F#F#F#F#F#F#F#F#F#F#F#F#F#F#F#F#F#F#F#F#F#F#F#F#F#F#F#F#F#F#F#F#G#H#I#J#J#J#J#J#J#J#J#J#J#J#J#KQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#L.7#C.X#l.V.3.N.4#d#e#m#t#D#M.Y.V#N#O#O#O#O#O#O#O#O#O#O#O#O#O#O#O#O#O#O#O#O#O#O#O#O#O#O#O#O#O#O#O#O#O#O#O#O#O#O#P.H#I#Q#Q#Q#Q#Q#Q#Q#Q#Q#Q#Q#Q#Q#Q#RQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#S.8.7#C.X#l.V.3.N.4#d#e#m#t#D#M#T#U#V#W#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#Y#Z#0#0#0#0#0#0#0#0#0#0#0#0#0#0#0#0#0#1QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#2#3.8.7#C.X#l.V.3.N.4#d#e#m#t#D#M#T#U#4#D#g#5#6#6#6#6#6#6#6#6#6#6#6#6#6#6#6#6#6#6#6#6#6#6#6#6#6#6#6#6#7#n.y#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#8#9QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQta.a##3.8.7#C.X#l.V.3.N.4#d#e#m#t#D#M#T#U#4aa.Bab#7acacacacacacacacacacacacacacacacacacacacacacacac#7.X.vadadadadadadadadadadadadadadadadadadadadadaeQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtafaga##3.8.7#C.X#l.V.3.N.4#d#e#m#t#D#M#T#U#4aa.yahaiajakakakakakakakakakakakakakakakakakakakakalamanaoaoaoaoaoaoaoaoaoaoaoaoaoaoaoaoaoaoaoaoaoaoaoapQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtaqaraga##3.8.7#C.X#l.V.3.N.4#d#e#m#t#D#M#T#U#4aa.yas.v#eatauauauauauauauauauauauauauauauauav#e#p#p#p#p#p#p#p#p#p#p#p#p#p#p#p#p#p#p#p#p#p#p#p#p#p#pawQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtax#oaraga##3.8.7#C.X#l.V.3.N.4#d#e#m#t#D#M#T#U#4aa.yas.vayazaAaBaCaCaCaCaCaCaCaCaCaCaDaEaFaGaGaGaGaGaGaGaGaGaGaGaGaGaGaGaGaGaGaGaGaGaGaGaGaGaGaGaGaHQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtaIaJ#oaraga##3.8.7#C.X#l.V.3.N.4#d#e#m#t#D#M#T#U#4aa.yas.vayaoaKaLaMaNaNaNaNaNaNaB#Y.BaOaOaOaOaOaOaOaOaOaOaOaOaOaOaOaOaOaOaOaOaOaOaOaOaOaOaOaOaOaOaPQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtaQaEaJ#oaraga##3.8.7#C.X#l.V.3.N.4#d#e#m#t#D#M#T#U#4aa.yas.vayao#zaRaSaTaUaUakaVaWaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaXQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtaYaZaEaJ#oaraga##3.8.7#C.X#l.V.3.N.4#d#e#m#t#D#M#T#U#4aa.yas.vayao#za0.pa1ai#4#4#4#4#4#4#4#4#4#4#4#4#4#4#4#4#4#4#4#4#4#4#4#4#4#4#4#4#4#4#4#4#4#4#4a2QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQta3a4aZaEaJ#oaraga##3.8.7#C.X#l.V.3.N.4#d#e#m#t#D#M#T#U#4aa.yas.vayao#za0.p#U#U#U#U#U#U#U#U#U#U#U#U#U#U#U#U#U#U#U#U#U#U#U#U#U#U#U#U#U#U#U#U#U#U#U#Ua5QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQta6a7a4aZaEaJ#oaraga##3.8.7#C.X#l.V.3.N.4#d#e#m#t#D#M#T#U#4aa.yas.vayao#za0.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.Ea8QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQta9b.a7a4aZaEaJ#oaraga##3.8.7#C.X#l.V.3.N.4#d#e#m#t#D#M#T#U#4aa.yas.vayao#zaFaFaFaFaFaFaFaFaFaFaFaFaFaFaFaFaFaFaFaFaFaFaFaFaFaFaFaFaFaFaFaFaFaFaFaFb#QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtbabbb.a7a4aZaEaJ#oaraga##3.8.7#C.X#l.V.3.N.4#d#e#m#t#D#M#T#U#4aa.yas.vayao#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#tbcQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtbdbebbb.a7a4aZaEaJ#oaraga##3.8.7#C.X#l.V.3.N.4#d#e#m#t#D#M#T#U#4aa.yas.vay#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#mbfQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtbgbhbebbb.a7a4aZaEaJ#oaraga##3.8.7#C.X#l.V.3.N.4#d#e#m#t#D#M#T#U#4aa.yas.vbibibibibibibibibibibibibibibibibibibibibibibibibibibibibibibibibibibibibjQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtbkblbhbebbb.a7a4aZaEaJ#oaraga##3.8.7#C.X#l.V.3.N.4#d#e#m#t#D#M#T#U#4aa.yas.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5bmQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtbnboblbhbebbb.a7a4aZaEaJ#oaraga##3.8.7#C.X#l.V.3.N.4#d#e#m#t#D#M#T#U#4aa.ybpbpbpbpbpbpbpbpbpbpbpbpbpbpbpbpbpbpbpbpbpbpbpbpbpbpbpbpbpbpbpbpbpbpbpbpbqbrQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtbs#6boblbhbebbb.a7a4aZaEaJ#oaraga##3.8.7#C.X#l.V.3.N.4#d#e#m#t#D#M#T#U#4aa.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3btbubvbwQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtbxby#6boblbhbebbb.a7a4aZaEaJ#oaraga##3.8.7#C.X#l.V.3.N.4#d#e#m#t#D#M#T#U#4.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.V.VbzbAbBbCbDbEQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtbFacby#6boblbhbebbb.a7a4aZaEaJ#oaraga##3.8.7#C.X#l.V.3.N.4#d#e#m#t#D#M#T#UbGbGbGbGbGbGbGbGbGbGbGbGbGbGbGbGbGbGbGbGbGbGbGbGbGbGbGbGbGbGbGbGbGbGbGbGbHbIbJbJbJbKbLbMQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtbNbOacby#6boblbhbebbb.a7a4aZaEaJ#oaraga##3.8.7#C.X#l.V.3.N.4#d#e#m#t#D#M#T.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.WbPbQbRbRbRbRbRbSbTbUbVQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtbWbXbOacby#6boblbhbebbb.a7a4aZaEaJ#oaraga##3.8.7#C.X#l.V.3.N.4#d#e#m#t#D#M.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7bYbZbLbLbLbLbLbLbLb0b1b2b3QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtb4b5bXbOacby#6boblbhbebbb.a7a4aZaEaJ#oaraga##3.8.7#C.X#l.V.3.N.4#d#e#m#t#D.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8b6b7b8b8b8b8b8b8b8b8b8b9c.c#caQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtcbccb5bXbOacby#6boblbhbebbb.a7a4aZaEaJ#oaraga##3.8.7#C.X#l.V.3.N.4#d#e#m#tcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcecfcgcgcgcgcgcgcgcgcgcgcgcgchcicjQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtckclccb5bXbOacby#6boblbhbebbb.a7a4aZaEaJ#oaraga##3.8.7#C.X#l.V.3.N.4#d#e#m#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#gcmcncococococococococococococococpcqcrQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtcsctclccb5bXbOacby#6boblbhbebbb.a7a4aZaEaJ#oaraga##3.8.7#C.X#l.V.3.N.4#d#ecucucucucucucucucucucucucucucucucucucucucucucucucucucucucucucucucucucucucvcwcxcxcxcxcxcxcxcxcxcxcxcxcxcxcxcxcyczcAQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtcBcCctclccb5bXbOacby#6boblbhbebbb.a7a4aZaEaJ#oaraga##3.8.7#C.X#l.V.3.N.4#d#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#o#ocDcEcFcFcFcFcFcFcFcFcFcFcFcFcFcFcFcFcFcFcGcHQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtcIcJcCctclccb5bXbOacby#6boblbhbebbb.a7a4aZaEaJ#oaraga##3.8.7#C.X#l.V.3.N.4#x#x#x#x#x#x#x#x#x#x#x#x#x#x#x#x#x#x#x#x#x#x#x#x#x#x#x#x#x#x#x#x#x#x#x#xcKcLcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcNcOcPcQcRQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtcScTcJcCctclccb5bXbOacby#6boblbhbebbb.a7a4aZaEaJ#oaraga##3.8.7#C.X#l.V.3.N#E#E#E#E#E#E#E#E#E#E#E#E#E#E#E#E#E#E#E#E#E#E#E#E#E#E#E#E#E#E#E#E#E#E#E#EcUcVcWcWcWcWcWcWcWcWcWcWcWcWcWcXcYcZc0c0c0c1QtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtc2aNcTcJcCctclccb5bXbOacby#6boblbhbebbb.a7a4aZaEaJ#oaraga##3.8.7#C.X#l.V.3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c4c5c6c6c6c6c6c6c6c6c6c6c6c7c8c9d.d.d.d.d.d#QtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtdadbaNcTcJcCctclccb5bXbOacby#6boblbhbebbb.a7a4aZaEaJ#oaraga##3.8.7#C.X#l.Va7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7dcdddedededededededededfdgdhdhdhdhdhdhdhdhdiQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtdjdkdbaNcTcJcCctclccb5bXbOacby#6boblbhbebbb.a7a4aZaEaJ#oaraga##3.8.7#C.X#ldldldldldldldldldldldldldldldldldldldldldldldldldldldldldldldldldldldldldmdndododododododpcxdqdrdrdrdrdrdrdrdrdrdrdsQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtdtdudkdbaNcTcJcCctclccb5bXbOacby#6boblbhbebbb.a7a4aZaEaJ#oaraga##3.8.7#C.XdvdvdvdvdvdvdvdvdvdvdvdvdvdvdvdvdvdvdvdvdvdvdvdvdvdvdvdvdvdvdvdvdvdvdvdvdwdxdydydydydzchdAdBdBdBdBdBdBdBdBdBdBdBdBdCQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtdDdEdudkdbaNcTcJcCctclccb5bXbOacby#6boblbhbebbb.a7a4aZaEaJ#oaraga##3.8.7#CajajajajajajajajajajajajajajajajajajajajajajajajajajajajajajajajajajajajdFdGdHdHdIdJdKdLdLdLdLdLdLdLdLdLdLdLdLdLdLdMQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtdNdOdEdudkdbaNcTcJcCctclccb5bXbOacby#6boblbhbebbb.a7a4aZaEaJ#oaraga##3.8.7dPdPdPdPdPdPdPdPdPdPdPdPdPdPdPdPdPdPdPdPdPdPdPdPdPdPdPdPdPdPdPdPdPdPdPdPdQdRdSdTdKdKdKdKdKdKdKdKdKdKdKdKdKdKdKdKdKdUQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtdVdWdOdEdudkdbaNcTcJcCctclccb5bXbOacby#6boblbhbebbb.a7a4aZaEaJ#oaraga##3.8dXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdXdYdZd0d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d1d2QtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtd3d4d5d6d7d8dEdudkdbaNcTcJcCctclccb5bXbOacby#6boblbhbebbb.a7a4aZaEaJ#oaraga##3d9d9d9d9d9d9d9d9d9d9d9d9d9d9d9d9d9d9d9d9d9d9d9d9d9d9d9d9d9d9d9d9d9e.e#eaebebebebebebebebebebebebebebebebebebebebebecQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtedeeefegeheiejekelemdudkdbaNcTcJcCctclccb5bXbOacby#6boblbhbebbb.a7a4aZaEaJ#oaraga#bybybybybybybybybybybybybybybybybybybybybybybybybybybybybybybyeneoepeqeqeqeqeqeqeqeqeqeqeqeqeqeqeqeqeqeqeqeqeqeqeqerQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQteseteuevevewexeyezeAeBeCeDeEeFdbaNcTcJcCctclccb5bXbOacby#6boblbhbebbb.a7a4aZaEaJ#oaragaTaTaTaTaTaTaTaTaTaTaTaTaTaTaTaTaTaTaTaTaTaTaTaTaTaTaTaTeGeHeIeJeJeJeJeJeJeJeJeJeJeJeJeJeJeJeJeJeJeJeJeJeJeJeJeJeJeKQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQteLeMeNeOeOeOeOeOeOePeQeReSeTeUeVeWeXeYaNcTcJcCctclccb5bXbOacby#6boblbhbebbb.a7a4aZaEaJ#oareZeZeZeZeZeZeZeZeZeZeZeZeZeZeZeZeZeZeZeZeZeZeZeZeZeZe0e1e2bBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBbBe3QtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQte4e5e6e7e7e7e7e7e7e7e7e7e7e8e9f.f#fafbfcfdfeffcTcJcCctclccb5bXbOacby#6boblbhbebbb.a7a4aZaEaJ#ob5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5fgfhfifjfjfjfjfjfjfjfjfjfjfjfjfjfjfjfjfjfjfjfjfjfjfjfjfjfjfjfjfjfjfkQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtflfmfnfnfnfnfnfnfnfnfnfnfnfnfnfnfnfofpfqfrfsftfufvfwfxcJcCctclccb5bXbOacby#6boblbhbebbb.a7a4aZaEaJaMaMaMaMaMaMaMaMaMaMaMaMaMaMaMaMaMaMaMaMaMaMfyfzbQfAfAfAfAfAfAfAfAfAfAfAfAfAfAfAfAfAfAfAfAfAfAfAfAfAfAfAfAfAfAfAfAfBQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtfCfDfEfEfEfEfEfEfEfEfEfEfEfEfEfEfEfEfEfEfEfFfGfHfIfJfKfLfMfNfOfPctclccb5bXbOacby#6boblbhbebbb.a7a4aZaEaBaBaBaBaBaBaBaBaBaBaBaBaBaBaBaBaBaBaBfQfRfSbRbRbRbRbRbRbRbRbRbRbRbRbRbRbRbRbRbRbRbRbRbRbRbRbRbRbRbRbRbRbRbRbRbRbRfTQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtfUfVfWfWfWfWfWfWfWfWfWfWfWfWfWfWfWfWfWfWfWfWfWfWfWfWfXfYfZf0f1f2f3f4f5f6clccb5bXbOacby#6boblbhbebbb.a7a4aZcCcCcCcCcCcCcCcCcCcCcCcCcCcCcCcCcCf7f8f9g.g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#gaQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtgbgcgdgegfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfggghgigjgkglgmgngogpccb5bXbOacby#6boblbhbebbb.a7a4gqgqgqgqgqgqgqgqgqgqgqgqgqgqgqgrgsgtgugvgwbLbLbLbLbLbLbLbLbLbLbLbLbLbLbLbLbLbLbLbLbLbLbLbLbLbLbLbLbLbLbLbLbLbLbLbLgxQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtgygzgcgAgBgegCgDgDgDgDgDgDgDgDgDgDgDgDgDgDgDgDgDgDgDgDgDgDgDgEgFgGgHgIgJgKgLgMgNb5bXbOacby#6boblbhbebbb.a7gOgOgOgOgOgOgOgOgOgOgOgOgOgPgQgRgSgTgTgTgUbTbTbTbTbTbTbTbTbTbTbTbTbTbTbTbTbTbTbTbTbTbTbTbTbTbTbTbTbTbTbTbTbTbTbTbTgVQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtgWgXgzgcgAgYgZg0g1g2g2g2g2g2g2g2g2g2g2g2g2g2g2g2g2g2g2g2g2g2g2g2g2g3g4g5g6g7g8g9h.h#habOacby#6boblbhbebbb.dbdbdbdbdbdbdbdbdbdbhbhchdhehfhghghghghghhb9b9b9b9b9b9b9b9b9b9b9b9b9b9b9b9b9b9b9b9b9b9b9b9b9b9b9b9b9b9b9b9b9b9b9b9hiQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQthjgegXgzgcgAgYe6hkgcgDhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhlhmhnhohphqhrhshthuhvacby#6boblbhbebbdkdkdkdkdkdkdkdkhwhxhyhzhAhAhAhAhAhAhAhAhBhChChChChChChChChChChChChChChChChChChChChChChChChChChChChChChChChChChChChDQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQthEhFgegXgzgcfngYe6hkhGgZhHhIhJhJhJhJhJhJhJhJhJhJhJhJhJhJhJhJhJhJhJhJhJhJhJhKhLhMhNhOhPhQhRhShTby#6boblbhbehUhUhUhUhUhUhVhWhXhYhZhZhZhZhZhZhZhZhZhZh0h1h1h1h1h1h1h1h1h1h1h1h1h1h1h1h1h1h1h1h1h1h1h1h1h1h1h1h1h1h1h1h1h1h1h1h1h2QtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQth3h4hFgegXgzgcfngYe6hkhGeOh5h4hKh6h6h6h6h6h6h6h6h6h6h6h6h6h6h6h6h6h6h6h6h6h6h6h7h8h9i.i#iaibicidie#6boblbhififififigihiiijikikikikikikikikikikikikilchchchchchchchchchchchchchchchchchchchchchchchchchchchchchchchchchchchchimQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtinioh4hFgegXgzgcfngYe6hkhGeOipiqirisititititititititititititititititititititititititiuiviwixiyiziAiBiCiDbliEiFiGiHhkiIiJiJiJiJiJiJiJiJiJiJiJiJiJiJiKiLiLiLiLiLiLiLiLiLiLiLiLiLiLiLiLiLiLiLiLiLiLiLiLiLiLiLiLiLiLiLiLiLiLiLiLiMQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtiNiOioh4hFgegXgzgcfngYe6hkhGeOipeviPgAiQiRiRiRiRiRiRiRiRiRiRiRiRiRiRiRiRiRiRiRiRiRiRiRiRiSiTiUiViWiXiYiZi0i1i2evi3i3i3i3i3i3i3i3i3i3i3i3i3i3i3i3i3i4i5i5i5i5i5i5i5i5i5i5i5i5i5i5i5i5i5i5i5i5i5i5i5i5i5i5i5i5i5i5i5i5i5i5i5i5i6QtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQti7gDiOioh4hFgegXgzgdfngYe6hkhGeOipeviPi8h5i9j.j#j#j#j#j#j#j#j#j#j#j#j#j#j#j#j#j#j#j#j#j#j#j#jajbjcjdjejfg1jgjhjhjhjhjhjhjhjhjhjhjhjhjhjhjhjhjhjhjhjijjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjkQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtjljmg1iOjnh4hFgegXgzgdfngYe6hkhGeOipeviPi8hejojpjqjrjrjrjrjrjrjrjrjrjrjrjrjrjrjrjrjrjrjrjrjrjrjrjrj.jshzjtjtjtjtjtjtjtjtjtjtjtjtjtjtjtjtjtjtjtjtjtjujvjvjvjvjvjvjvjvjvjvjvjvjvjvjvjvjvjvjvjvjvjvjvjvjvjvjvjvjvjvjvjvjvjvjvjvjwQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtjxjyjmg1iOjnh4hFgegXgzgdjzgYe6hkhGeOipeviPi8hejAjBjCjDjEjEjEjEjEjEjEjEjEjEjEjEjEjEjEjEjEjEjEjEjFjGjHjIjIjIjIjIjIjIjIjIjIjIjIjIjIjIjIjIjIjIjIjIjIjIjJc7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7jKQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtjLjMjyjmg1iOjnh4hFgegXfEgdjzgYe6jNhGeOipeviPi8hejAjOjPjQjRjSjSjSjSjSjSjSjSjSjSjSjSjSjSjSjSjRjQjHjHjHjHjHjHjHjHjHjHjHjHjHjHjHjHjHjHjHjHjHjHjHjHjHjHjTcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMjUQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtjVjWjMjyjXg1iOjnh4hFgegXfEgdjzgYe6jNhGeOipeviPi8hejAjOjPjYjZj0j1j2j2j2j2j2j2j2j2j2j2j1j3j4jPjPjPjPjPjPjPjPjPjPjPjPjPjPjPjPjPjPjPjPjPjPjPjPjPjPjPjPj5j6j6j6j6j6j6j6j6j6j6j6j6j6j6j6j6j6j6j6j6j6j6j6j6j6j6j6j6j6j6j6j6j6j6j6j6j7QtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtj8j9jWjMjyjXg1iOk.h4hFgegXfEgdjzgYe6jNhGeOipeviPi8hejAjOjPjYk#kakbkckdkdkdkdkdkdkekfkgkhkhkhkhkhkhkhkhkhkhkhkhkhkhkhkhkhkhkhkhkhkhkhkhkhkhkhkhkhkhkikjkjkjkjkjkjkjkjkjkjkjkjkjkjkjkjkjkjkjkjkjkjkjkjkjkjkjkjkjkjkjkjkjkjkjkjkkQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtklhIkmjWjMjyjXg1iOk.h4hFgegXfEgdjzgYe6jNhGeOipeviPi8hejAjOjPjYhYknkokpkqkrkrksktkukvkvkvkvkvkvkvkvkvkvkvkvkvkvkvkvkvkvkvkvkvkvkvkvkvkvkvkvkvkvkvkvkwkxkxkxkxkxkxkxkxkxkxkxkxkxkxkxkxkxkxkxkxkxkxkxkxkxkxkxkxkxkxkxkxkxkxkxkxkyQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtkzkAhIkmjWjMjyjXkBiOk.h4hFgegXfEgdjzgYe6jNh5eOipeviPi8hejAjOjPjYhYknjtjhkCkDi8i8i8i8i8i8i8i8i8i8i8i8i8i8i8i8i8i8i8i8i8i8i8i8i8i8i8i8i8i8i8i8i8i8i8kEkFkFkFkFkFkFkFkFkFkFkFkFkFkFkFkFkFkFkFkFkFkFkFkFkFkFkFkFkFkFkFkFkFkFkFkFkGQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtkHkIkAhIkmjWjMjyjXkBiOk.h4hFgekJfEgdjzgYe6jNh5eOkKeviPkuhejAjOjPjYhYknjtjhiPiPiPiPiPiPiPiPiPiPiPiPiPiPiPiPiPiPiPiPiPiPiPiPiPiPiPiPiPiPiPiPiPiPiPiPkLkMkMkMkMkMkMkMkMkMkMkMkMkMkMkMkMkMkMkMkMkMkMkMkMkMkMkMkMkMkMkMkMkMkMkMkMkNQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtkOh6kIkAhIkmjWjMg2jXkBiOk.h4hFgeirfEgdjzgYe6jNh5eOkKeviPkuhejAjOkPjYhYknjtevevevevevevevevevevevevevevevevevevevevevevevevevevevevevevevevevevevevkQkRkRkRkRkRkRkRkRkRkRkRkRkRkRkRkRkRkRkRkRkRkRkRkRkRkRkRkRkRkRkRkRkRkRkRkRkSQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtkTkUh6kIkAhIkmjWjMg2jXkBiOk.h4hFgeirfEgdjzgYe6jNh5eOkKeviPkVhejAkWkPjYhYknkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkYdpdpdpdpdpdpdpdpdpdpdpdpdpdpdpdpdpdpdpdpdpdpdpdpdpdpdpdpdpdpdpdpdpdpdpdpkZQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtk0itkUk1kIkAhIkmjWjMg2jXkBiOk.h4hFk2irfEgdjziie6k3h5eOkKeviPkVhejAkWkPjYk4hGhGhGhGhGhGhGhGhGhGhGhGhGhGhGhGhGhGhGhGhGhGhGhGhGhGhGhGhGhGhGhGhGhGhGhGk5k6k6k6k6k6k6k6k6k6k6k6k6k6k6k6k6k6k6k6k6k6k6k6k6k6k6k6k6k6k6k6k6k6k6k6k6k7QtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtk8k9itkUk1kIkAhIl.jWjMg2jXkBiOk.h4hFfWirfEgdjziie6k3h5eOkKeviPkVhejAkWkPjYhkhkhkhkhkhkhkhkhkhkhkhkhkhkhkhkhkhkhkhkhkhkhkhkhkhkhkhkhkhkhkhkhkhkhkhkl#dydydydydydydydydydydydydydydydydydydydydydydydydydydydydydydydydydydydylaQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtlblck9itkUk1kIkAhIl.jWldg2jXkBiOk.h4hFfWirfEgdjziie6k3h5eOkKeviPkVhejAkWkPe6e6e6e6e6e6e6e6e6e6e6e6e6e6e6e6e6e6e6e6e6e6e6e6e6e6e6e6e6e6e6e6e6e6e6e6lelflflflflflflflflflflflflflflflflflflflflflflflflflflflflflflflflflflflflgQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtlhlilck9itkUk1kIkAhIl.jWldi9ljkBiOk.h4hFfWirfEgdjziie6k3h5eOkKeviPkVhejAkWiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiilkdHdHdHdHdHdHdHdHdHdHdHdHdHdHdHdHdHdHdHdHdHdHdHdHdHdHdHdHdHdHdHdHdHdHdHdHllQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtlmlnliiRk9itlok1kIlphIl.jWldi9ljkBiOk.h4lqfWirfEgdjziikCk3h5eOkKevjokVhejAjzjzjzjzjzjzjzjzjzjzjzjzjzjzjzjzjzjzjzjzjzjzjzjzjzjzjzjzjzjzjzjzjzjzjzjzlrlslslslslslslslslslslslslslslslslslslslslslslslslslslslslslslslslslslslsltQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtlulvlnliiRk9itlok1kIlphIl.jWldi9ljkBiOk.lwlqfWirfEgdjziikCk3h5eOkKevjokVhegzgzgzgzgzgzgzgzgzgzgzgzgzgzgzgzgzgzgzgzgzgzgzgzgzgzgzgzgzgzgzgzgzgzgzgzlxlylylylylylylylylylylylylylylylylylylylylylylylylylylylylylylylylylylylylzQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtlAlBlvlnliiRk9itlok1kIlphIl.jWldi9ljkBiOk.lwlqfWirfEgdjziikCk3h5eOkKevjokVgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXlClDlDlDlDlDlDlDlDlDlDlDlDlDlDlDlDlDlDlDlDlDlDlDlDlDlDlDlDlDlDlDlDlDlDlDlElFQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtlGlHlBlvlIliiRk9itlok1kIlphIl.jWldi9ljkBiOk.lwlqfWirfEgdjziikCk3lJeOkKevjofWfWfWfWfWfWfWfWfWfWfWfWfWfWfWfWfWfWfWfWfWfWfWfWfWfWfWfWfWfWfWfWfWfWfWfWlKlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlLlMlNQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtlOlPlHlBlvlIliiRk9itlok1kIlphIl.jWldi9ljkBiOk.gflqfWirfElQjziikCk3lJeOkKevlqlqlqlqlqlqlqlqlqlqlqlqlqlqlqlqlqlqlqlqlqlqlqlqlqlqlqlqlqlqlqlqlqlqlqlqlRlSlSlSlSlSlSlSlSlSlSlSlSlSlSlSlSlSlSlSlSlSlSlSlSlSlSlSlSlSlSlSlTlUQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtlVjElWlHlBlvj#liiRk9itlok1kIlphIlXjWldi9ljkBiOk.gflqfWirfElQjzgAkCk3lJeOkKgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgflYlZlZlZlZlZlZlZlZlZlZlZlZlZlZlZlZlZlZlZlZlZlZlZlZlZlZlZlZl0l1l2QtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtl3l4jElWlHlBlvj#liiRk9l5lok1kIlphIlXhlldi9ljkBiOk.gflqfWirfElQjzgAkCk3lJeOiOiOiOiOiOiOiOiOiOiOiOiOiOiOiOiOiOiOiOiOiOiOiOiOiOiOiOiOiOiOiOiOiOiOiOiOl6l7l7l7l7l7l7l7l7l7l7l7l7l7l7l7l7l7l7l7l7l7l7l7l7l7l7l8l9QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtm.jSl4jElWlHlBlvj#liiRk9l5lok1kIlphIlXhlldi9ljkBiOm#gflqfWirfElQjzgAkCk3lJkBkBkBkBkBkBkBkBkBkBkBkBkBkBkBkBkBkBkBkBkBkBkBkBkBkBkBkBkBkBkBkBkBkBkBkBmambmbmbmbmbmbmbmbmbmbmbmbmbmbmbmbmbmbmbmbmbmbmbmbmcmdQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtmemfjSl4jElWmglBlvj#liiRk9l5lomhkIlphIlXhlldi9ljkBiOm#gflqfWirfElQjzgAkCk3ljljljljljljljljljljljljljljljljljljljljljljljljljljljljljljljljljljljljmimjmjmjmjmjmjmjmjmjmjmjmjmjmjmjmjmjmjmjmjmjmjmkmlQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtmmmnmfjSl4jElWmglBlvj#liiRk9l5lomhkIlpmolXhlldi9ljkBmpm#gflqfWirfElQjzgAkCi9i9i9i9i9i9i9i9i9i9i9i9i9i9i9i9i9i9i9i9i9i9i9i9i9i9i9i9i9i9i9i9i9i9i9i9mqmrmrmrmrmrmrmrmrmrmrmrmrmrmrmrmrmrmrmrmsmtmuQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtmvmwmnmfjSl4jElWmglBmxj#liiRk9l5lomhkIlpmolXhlldi9ljkBmym#gflqfWirfElQjzgAjWjWjWjWjWjWjWjWjWjWjWjWjWjWjWjWjWjWjWjWjWjWjWjWjWjWjWjWjWjWjWjWjWjWjWjWmzmAmAmAmAmAmAmAmAmAmAmAmAmAmAmAmAmAmBmCQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtmDmEmFmnmfjSl4jElWmgmGmxj#liiRk9l5lomhkIlpmolXhlldi9ljkBmym#gflqfWgefElQjzj9j9j9j9j9j9j9j9j9j9j9j9j9j9j9j9j9j9j9j9j9j9j9j9j9j9j9j9j9j9j9j9j9j9j9j9mHmImImImImImImImImImImImImImImImJmKQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtmLmMmEmFmnmfjSl4jElWmgmGmxj#liiRk9l5lomhkIlpmolXhlldi9ljkBmym#gflqfWgefElQhIhIhIhIhIhIhIhIhIhIhIhIhIhIhIhIhIhIhIhIhIhIhIhIhIhIhIhIhIhIhIhIhIhIhIhImNmOmOmOmOmOmOmOmOmOmOmOmOmOmPmQQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtmRmSmMmEmFmnmfjSl4jElWmgmGmxj#liiRmTl5lomhkIlpmolXhlldi9ljkBmym#gflqfWgefElplplplplplplplplplplplplplplplplplplplplplplplplplplplplplplplplplplplpmUmVmVmVmVmVmVmVmVmVmVmWmXmYQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtmZkrmSmMm0mFmnmfjSl4jElWmgmGmxj#liiRmTl5lomhkIm1molXhlldi9m2m3mym#gfm4fWgeh6h6h6h6h6h6h6h6h6h6h6h6h6h6h6h6h6h6h6h6h6h6h6h6h6h6h6h6h6h6h6h6h6h6h6h6m5m6m6m6m6m6m6m6m6m7m8QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtm9n.krmSmMm0mFmnmfjSl4jElWmgmGmxj#liiRmTl5lomhkIm1hJlXhlldi9m2m3mym#gfm4fWkUkUkUkUkUkUkUkUkUkUkUkUkUkUkUkUkUkUkUkUkUkUkUkUkUkUkUkUkUkUkUkUkUkUkUkUn#nananananananbncQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtndnen.krmSmMm0mFj2mfjSl4jElWmgmGmxj#liiRmTl5lomhkIm1hJlXhlldi9m2m3mym#gfm4ititititititititititititititititititititititititititititititititititititnfngngngngnhniQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtnjnknen.krmSmMm0mFj2mfjSnlnmlWmgmGmxj#j.iRmTl5lomhkIm1hJlXhlnni9m2m3mym#gfk9k9k9k9k9k9k9k9k9k9k9k9k9k9k9k9k9k9k9k9k9k9k9k9k9k9k9k9k9k9k9k9k9k9k9k9nonpnqnrQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtnsntnknen.krmSmMm0mFj2kejSnlnmlWmgmGmxj#j.iRmTl5lomhkIm1hJlXhlnni9m2m3mym#nununununununununununununununununununununununununununununununununununununvnwQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtnxnyntnknen.krmSmMm0mFj2kejSnlnmlWmgnzmxj#j.numTl5lomhh6m1hJlXhlnni9jym3mynAnAnAnAnAnAnAnAnAnAnAnAnAnAnAnAnAnAnAnAnAnAnAnAnAnAnAnAnAnAnAnAnAnAnAnBnCQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtnDnEnknen.krmSmMm0mFj2nFjSnlnmlWmgjrmxj#j.numTnGlomhh6m1hJlXhlnni9jym3nHnHnHnHnHnHnHnHnHnHnHnHnHnHnHnHnHnHnHnHnHnHnHnHnHnHnHnHnHnHnHnHnHnInJQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtnKnLnen.krmSmMm0nMj2nFjSnlnmlWmgjrmxj#j.numTnGlomhh6m1hJlXhlnnnNjylBlBlBlBlBlBlBlBlBlBlBlBlBlBlBlBlBlBlBlBlBlBlBlBlBlBlBlBlBlBlBnOnPQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtnQnRnSkrmSmMm0nMj2nFjSnlnmlWmgjrmxj#j.numTnGlomhh6m1hJlXhlnTnNmgmgmgmgmgmgmgmgmgmgmgmgmgmgmgmgmgmgmgmgmgmgmgmgmgmgmgmgnUnVnWQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtnXnYmSmMm0nMj2nFjSnlnmlWmgjrmxj#j.numTnGlomhh6m1hJlXhlnTlWlWlWlWlWlWlWlWlWlWlWlWlWlWlWlWlWlWlWlWlWlWlWlWlWlWnZn0QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtn1n2mMm0nMj2nFjSnlnmlWmgjrmxj#j.numTnGlokUh6m1hJlXhln3n3n3n3n3n3n3n3n3n3n3n3n3n3n3n3n3n3n3n3n3n3n3n3n4n5QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtn6n7m0nMj2nFjSnlnmlWmgjrmxj#j.numTnGlokUh6m1hJlXn8n8n8n8n8n8n8n8n8n8n8n8n8n8n8n8n8n8n8n8n8n8n9o.QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQto#oaobj2nFjSocn3lWmgjrmxj#nAnumTnGlokUh6m1hJmfmfmfmfmfmfmfmfmfmfmfmfmfmfmfmfmfmfmfodoeofQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtogohnFjSocn3lWoijrmxj#nAnumTnGlokUh6m1j2j2j2j2j2j2j2j2j2j2j2j2j2j2j2j2j2ohojQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtokoljSocn3lWoijrmxj#nAnumTnGlokUh6nMnMnMnMnMnMnMnMnMnMnMnMnMnMnMomonQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtooopocn3lWoijrmxj#nAnumTnGoqkUkdkdkdkdkdkdkdkdkdkdkdkdkdorosQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtotouovlWoijrmxj#nAnumTnGoqmSmSmSmSmSmSmSmSmSmSowoxoyQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtozoAoijrmxj#nAnumTnGkrkrkrkrkrkrkrkroBoCQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtoDoEjrmxj#nAnumToFoFoFoFoFoFoGoHQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtoIoJoKnHnAnuoLoLoLoLoMoNQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtoOoPoQnAoRoSoToUQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtoVoWQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt"};
'
where id_io_category = 53 and (id_io_attribute in (78, 90));

update attrs_categories set def_value = '1' where id_io_category = 53 and id_io_attribute = 83;

commit;
